# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/03Pines/Arty-Z7-20-Master.xdc

# Block Designs: bd/Gen_clk/Gen_clk.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Gen_clk || ORIG_REF_NAME==Gen_clk} -quiet] -quiet

# IP: bd/Gen_clk/ip/Gen_clk_clk_wiz_0_0/Gen_clk_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Gen_clk_clk_wiz_0_0 || ORIG_REF_NAME==Gen_clk_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/Gen_clk/Gen_clk_ooc.xdc
