# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0.xci
# IP: The module: 'clock_unit_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0.xci
# IP: The module: 'clock_unit_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
