# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Ceci/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-1600-DESKTOP-DUF9KV0/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.cache/wt [current_project]
set_property parent.project_path D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Users/Ceci/Documents/Facu/digisist/GHDL/CORDIC/CORDIC_IT.vhd
  D:/Users/Ceci/Documents/Facu/digisist/GHDL/delay/my_library.vhd
  D:/Users/Ceci/Documents/Facu/digisist/GHDL/CORDIC/CORDIC_top.vhd
  D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/imports/hdl/clock_unit_wrapper.vhd
  D:/Users/Ceci/Documents/Facu/digisist/GHDL/delay/delay.vhd
  D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/imports/Ejemplos_TP2/arcvga/02VGAVideoMem/gen_pixels.vhd
  D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/imports/Ejemplos_TP2/UART_Fuentes/meta_harden.vhd
  D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/imports/Ejemplos_TP2/UART_Fuentes/uart_baud_gen.vhd
  D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/imports/Ejemplos_TP2/UART_Fuentes/uart_rx.vhd
  D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/imports/Ejemplos_TP2/UART_Fuentes/uart_rx_ctl.vhd
  D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/imports/Ejemplos_TP2/arcvga/02VGAVideoMem/vga_sync.vhd
  D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/imports/Ejemplos_TP2/arcvga/02VGAVideoMem/vga_ctrl.vhd
  D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/imports/hdl/video_mem_wrapper.vhd
  D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/new/girador.vhd
}
add_files D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/video_mem/video_mem.bd
set_property used_in_implementation false [get_files -all d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/video_mem/ip/video_mem_blk_mem_gen_0_0/video_mem_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/video_mem/video_mem_ooc.xdc]

add_files D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/clock_unit.bd
set_property used_in_implementation false [get_files -all d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/ip/clock_unit_clk_wiz_0_0/clock_unit_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/bd/clock_unit/clock_unit_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/constrs_1/imports/04PinesVGAVideoMem/Arty-Z7-20-Master.xdc
set_property used_in_implementation false [get_files D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/constrs_1/imports/04PinesVGAVideoMem/Arty-Z7-20-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top girador -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef girador.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file girador_utilization_synth.rpt -pb girador_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
