# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/gen_clk/ip/gen_clk_clk_wiz_0_0/gen_clk_clk_wiz_0_0.xci
# IP: The module: 'gen_clk_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/gen_clk/ip/gen_clk_clk_wiz_0_0/gen_clk_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/gen_clk/ip/gen_clk_clk_wiz_0_0/gen_clk_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/gen_clk/ip/gen_clk_clk_wiz_0_0/gen_clk_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/gen_clk/ip/gen_clk_clk_wiz_0_0/gen_clk_clk_wiz_0_0.xci
# IP: The module: 'gen_clk_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/gen_clk/ip/gen_clk_clk_wiz_0_0/gen_clk_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/gen_clk/ip/gen_clk_clk_wiz_0_0/gen_clk_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/gen_clk/ip/gen_clk_clk_wiz_0_0/gen_clk_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gen_clk_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
