# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/video_mem/video_mem.xci
# IP: The module: 'video_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/video_mem/video_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/video_mem/video_mem.xci
# IP: The module: 'video_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/video_mem/video_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
