webtalk_init -webtalk_dir /home/cecilia/Documentos/Sistemas_digitales/digisist/Vivado2018/TP3/TP3.sim/sim_1/behav/xsim/xsim.dir/mulPF_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov  7 11:15:40 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "958fcaec-00d1-42bf-a15e-f29e203cbe9a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5a30a572e93e474e85e142f8d38013c4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Athlon(tm) II X2 270 Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "800.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "133116_KB" -context "xsim\\usage"
webtalk_transmit -clientid 706815551 -regid "" -xml /home/cecilia/Documentos/Sistemas_digitales/digisist/Vivado2018/TP3/TP3.sim/sim_1/behav/xsim/xsim.dir/mulPF_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/cecilia/Documentos/Sistemas_digitales/digisist/Vivado2018/TP3/TP3.sim/sim_1/behav/xsim/xsim.dir/mulPF_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/cecilia/Documentos/Sistemas_digitales/digisist/Vivado2018/TP3/TP3.sim/sim_1/behav/xsim/xsim.dir/mulPF_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
