# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/video_mem/ip/video_mem_blk_mem_gen_0_0/video_mem_blk_mem_gen_0_0.xci
# IP: The module: 'video_mem_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/video_mem/ip/video_mem_blk_mem_gen_0_0/video_mem_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_mem_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/video_mem/ip/video_mem_blk_mem_gen_0_0/video_mem_blk_mem_gen_0_0.xci
# IP: The module: 'video_mem_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/barbe_000/Desktop/U/sistemas digitales/tp2/2/mem_vid/mem_vid.srcs/sources_1/bd/video_mem/ip/video_mem_blk_mem_gen_0_0/video_mem_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_mem_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
