webtalk_init -webtalk_dir D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/CORDIC_v2/CORDIC_v2.sim/sim_1/behav/xsim/xsim.dir/CORDIC_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug 13 18:49:00 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7314ce79-8fa9-43c5-9f4f-88d600b3f078" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e354bad1967d4a47b72b8a5eb5b60773" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Athlon(tm) II X2 270 Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3415 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "290 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.39_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5548_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2267151823 -regid "" -xml D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/CORDIC_v2/CORDIC_v2.sim/sim_1/behav/xsim/xsim.dir/CORDIC_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/CORDIC_v2/CORDIC_v2.sim/sim_1/behav/xsim/xsim.dir/CORDIC_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Users/Ceci/Documents/Facu/digisist/Vivado2018/CORDIC_v2/CORDIC_v2.sim/sim_1/behav/xsim/xsim.dir/CORDIC_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
