# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digisist/Ejemplos_TP2/arcvga/04PinesVGAVideoMem/Arty-Z7-20-Master.xdc

# Block Designs: bd/video_mem/video_mem.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_mem || ORIG_REF_NAME==video_mem} -quiet] -quiet

# IP: bd/video_mem/ip/video_mem_blk_mem_gen_0_0/video_mem_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==video_mem_blk_mem_gen_0_0 || ORIG_REF_NAME==video_mem_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/gen_clk/gen_clk.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gen_clk || ORIG_REF_NAME==gen_clk} -quiet] -quiet

# IP: bd/gen_clk/ip/gen_clk_clk_wiz_0_0/gen_clk_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gen_clk_clk_wiz_0_0 || ORIG_REF_NAME==gen_clk_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/video_mem/video_mem_ooc.xdc

# XDC: bd/gen_clk/gen_clk_ooc.xdc
