# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/clock_unit/clock_unit.xci
# IP: The module: 'clock_unit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/clock_unit/clock_unit_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/clock_unit/clock_unit.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/clock_unit/clock_unit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/clock_unit/clock_unit.xci
# IP: The module: 'clock_unit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/clock_unit/clock_unit_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/clock_unit/clock_unit.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Ceci/Documents/Facu/digisist/Vivado2018/Girador/Girador.srcs/sources_1/ip/clock_unit/clock_unit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_unit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
